# Generated by Django 5.2.8 on 2026-01-07 10:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='car',
            name='production_date',
        ),
        migrations.AddField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='deposit',
            field=models.DecimalField(decimal_places=0, default=50000, max_digits=10, verbose_name='Kaució (Ft)'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Benzin', 'Benzin'), ('Dízel', 'Dízel'), ('Elektromos', 'Elektromos'), ('Hibrid', 'Hibrid')], default='benzin', max_length=20, verbose_name='Üzemanyag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default=1, max_length=50, verbose_name='Modell'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manuális', 'Manuális'), ('Automata', 'Automata')], default='', max_length=20, verbose_name='Váltó'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2023, verbose_name='Évjárat'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Márka'),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.category', verbose_name='Kategória'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, verbose_name='Leírás'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drivetrain',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Hajtáslánc'),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=10, unique=True, verbose_name='Rendszám'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Napi ár (Ft)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='technical_exam_date',
            field=models.DateField(blank=True, null=True, verbose_name='Műszaki vizsga'),
        ),
    ]
