# Generated by Django 5.2.8 on 2026-01-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_insurance_remove_car_production_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='car',
            options={},
        ),
        migrations.RemoveField(
            model_name='car',
            name='consumption',
        ),
        migrations.RemoveField(
            model_name='car',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.RemoveField(
            model_name='car',
            name='drivetrain',
        ),
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='car',
            name='technical_exam_date',
        ),
        migrations.AddField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Benzin', 'Benzin'), ('Dízel', 'Dízel'), ('Elektromos', 'Elektromos'), ('Hibrid', 'Hibrid')], default='Benzin', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manuális', 'Manuális'), ('Automata', 'Automata')], default='Manuális', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
