# Generated by Django 5.2.8 on 2026-01-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_car_category_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
