# Generated by Django 5.2.8 on 2025-11-23 18:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('first_name', models.CharField(max_length=32, verbose_name='Keresztnév')),
                ('last_name', models.CharField(max_length=32, verbose_name='Vezetéknév')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Születési dátum')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='A telefonszámnak 11 számjegyből kell állnia.', regex='^\\d{11}$')], verbose_name='Telefonszám')),
                ('zip_code', models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(message='Az irányítószám 4 számjegyű.', regex='^\\d{4}$')], verbose_name='Irányítószám')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lakcím')),
                ('id_card_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Személyi ig. / Lakcímkártya szám')),
                ('id_card_image_front', models.ImageField(blank=True, null=True, upload_to='documents/id_cards/', verbose_name='Személyi ig. előlap')),
                ('id_card_image_back', models.ImageField(blank=True, null=True, upload_to='documents/id_cards/', verbose_name='Személyi ig. hátlap')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Hitelesített felhasználó')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Felhasználó',
                'verbose_name_plural': 'Felhasználók',
            },
        ),
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Kategória')),
                ('issue_date', models.DateField(verbose_name='Kiállítás dátuma')),
                ('expiry_date', models.DateField(verbose_name='Lejárat dátuma')),
                ('license_number', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='A jogosítvány szám formátuma: 2 betű és 6 számjegy (pl. AB123456).', regex='^[A-Z]{2}\\d{6}$')], verbose_name='Jogosítvány szám')),
                ('license_image_front', models.ImageField(blank=True, null=True, upload_to='documents/licenses/', verbose_name='Jogosítvány előlap')),
                ('license_image_back', models.ImageField(blank=True, null=True, upload_to='documents/licenses/', verbose_name='Jogosítvány hátlap')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
